### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by DuSky0225** [livekit/swift-krisp-noise-filter#1]
Uncaught (in promise) Error: Authentication Error. Code 25683
    at lI.rE (index.js:16668:11)
    at lI.setEnabled (index.js:16645:40)
    at o.B (index.js:16628:58)
    at o._onWasmWorkerMessage (index.js:15959:93)

**Comment by lukasIO** [comment]
Are you using this with LiveKit cloud or with a self hosted LiveKit server?

The krisp noise filter only works for LiveKit cloud projects.
